CREATE USER i2b2pm IDENTIFIED BY demouser;
CREATE USER i2b2hive IDENTIFIED BY demouser;
CREATE USER i2b2metadata IDENTIFIED BY demouser;
CREATE USER i2b2workdata IDENTIFIED BY demouser;
CREATE USER i2b2sampledata IDENTIFIED BY demouser;
CREATE USER i2b2demodata IDENTIFIED BY demouser;
CREATE USER i2b2imdata IDENTIFIED BY demouser;

ALTER USER i2b2pm QUOTA UNLIMITED ON SYSTEM;
ALTER USER i2b2hive quota UNLIMITED ON SYSTEM;
ALTER USER i2b2metadata QUOTA UNLIMITED ON SYSTEM;
ALTER USER i2b2workdata QUOTA UNLIMITED ON SYSTEM;
ALTER USER i2b2sampledata QUOTA UNLIMITED ON SYSTEM;
ALTER USER i2b2demodata QUOTA UNLIMITED ON SYSTEM;
ALTER USER i2b2imdata QUOTA UNLIMITED ON SYSTEM;

GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2pm;
GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2hive;
GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2metadata;
GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2workdata;
GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2sampledata;
GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2demodata;
GRANT CREATE ANY PROCEDURE, GRANT ANY ROLE, CREATE ANY SEQUENCE, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY TYPE, CREATE ANY VIEW, CREATE SESSION TO i2b2imdata;

commit;

exit;
